// angular/src/app/myform/myform.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-myform',
  templateUrl: './myform.component.html',
  styleUrls: ['./myform.component.css'],
})
export class MyformComponent {
  height: number;
  weight: number;
  result: number;
  calculate() {
    this.result = parseFloat((this.weight / this.height ** 2).toFixed(2));
  }
}

<form>
  <label
    >Height in m
    <input
      type="number"
      autofocus
      [(ngModel)]="height"
      name="height"
      (change)="calculate()"
    />
  </label>
  <label
    >Weight in kg
    <input
      type="number"
      [(ngModel)]="weight"
      name="weight"
      (change)="calculate()"
    />
  </label>

  Result: {{ result }}
</form>

// reactjs/src/MyForm.js
import { useState } from "react";

function MyForm() {
  const [height, setHeight] = useState(0);
  const [weight, setWeight] = useState(0);
  return (
    <form>
      <label>
        Height in m
        <input
          type="number"
          autofocus
          value={height}
          onChange={(e) => setHeight(e.target.value)}
        />
      </label>
      <label>
        Weight in kg
        <input
          type="number"
          value={weight}
          onChange={(e) => setWeight(e.target.value)}
        />
      </label>
      Result: {(weight / height ** 2).toFixed(2)}
    </form>
  );
}

export default MyForm;
